### ISSUE TITLE
Ripensare da zero il building (homepage, archivio, blog post)

### ISSUE THREAD

**Issue by dennisangemi** [dennisangemi/hildegard#11]
Attualmente il processo è gestito (malissimo) da `./build` che chiama `./scripts/build_page` che a sua volta chiama `scripts/suggeritore.py`.

## Task
Ripensare completamente il processo di creazione home page e pagine di archivio. Mentre ci sei, implementa pure creazione di blog post automatici tramite `./scripts/functions/build_hai_suggestions_blog_post` (che è scritta meglio di tutto il resto). 

- [ ] #23 
- [x] disegnare una migliore home #73 
- [x] costruire homepage
- [x] costruire pagina di archivio
- [ ] gestire i metadati delle pagine di archivio #34
- [x] #81
- [ ] #26 
- [ ] #56
- [x] #57 
- [x] #61 
- [x] evitare la creazione di duplicati in nav
- [x] includere nel processo di build anche la creazione del blog post powered by ai #66 
- [ ] linkare l'ultimo blog post in homepage #72
